gravitational/shared-workflows

.github/workflows/dependency-review.yaml
Dependency Review Action
This Action will scan dependency manifest files that change as part of a Pull Request, surfacing known-vulnerable versions of the packages declared or updated in the PR. Once installed, if the workflow run is marked as required, PRs introducing known-vulnerable packages will be blocked from merging.
Source repository: https://github.com/actions/dependency-review-action
Public documentation: https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-dependency-review#dependency-review-enforcement
=> Add GitHub's dependency-review-action as a linter

bot/internal/bot/assign.go, bot/internal/bot/check.go, bot/internal/review/review.go, bot/internal/review/review_test.go
Should be a no-op for gravitational/teleport.
Just flips logic around for some review logic when in 'cloud' repo vs. 'teleport'
=> CLOUD RFD-0029: Support running against teleport *and* cloud repos

bot/internal/bot/assign.go, bot/internal/bot/bot.go, bot/internal/bot/bot_test.go, bot/internal/bot/check.go, bot/internal/env/env.go, bot/internal/review/review.go
The `classifyChanges` function determines whether a file path includes `/docs` and chooses different reviewers. This should only apply to the Teleport repo.
In order to support a repo comparison, the repo and teams constants were moved from the review package to the env package.
=> Limit classify changes to Teleport repo

bot/internal/review/review.go, bot/internal/review/review_test.go
This allows dependabot to follow the "regular" review cycle, making its dependency update PRs more practical to work with.
=> Treat dependabot as an internal contributor

bot/internal/review/review.go
Example failure log containing the correct author string: https://github.com/gravitational/teleport/actions/runs/3183541203/jobs/5190885027.
=> Use correct author for Dependabot

.github/workflows/terraform-lint.yaml
Reverts gravitational/shared-workflows#34 due to https://github.com/aquasecurity/tfsec-pr-commenter-action/issues/85.
=> Revert "Bump aquasecurity/tfsec-pr-commenter-action from 1.2.0 to 1.3.0"

bot/internal/bot/bot.go, bot/internal/bot/bot_test.go
Currently, changes to `CHANGELOG.md` are treated as code changes.
PRs to the docs in `gravitational/teleport` often need to edit `CHANGELOG.md` as well, since `docs/pages/changelog.mdx` includes `CHANGELOG.md` as a partial, and it's often necessary to, say, fix links in `CHANGELOG.md` in order to get the docs linter to pass.
If `CHANGELOG.md` is treated as a code change, docs PRs that edit this file need to get two more approvals in order to be merged, even if they don't touch any of the `gravitational/teleport` code.
This change treats `CHANGELOG.md` as a special case for determining that a PR is a docs PR. Other Markdown files outside of `docs/` still require code approval, since the assumption is that these are only relevant to the Engineering team.
=> Mark CHANGELOG changes as docs only

.github/workflows/dependency-review.yaml
Add a few more licenses, as well as the SPDX full strings for some licenses, as the currently released version of `dependency-review-action` does not parse SPDX licenses correctly.
Note that this can be cleaned-up once
https://github.com/actions/dependency-review-action/pull/294 is released.
=> dependency-review: Add additional approved licenses

.github/workflows/dependency-review.yaml
The syntax I previously attempted failed, so reverting to space-deliminated licenses.
Additionally, add a few more licenses that we are OK with.
=> dependency-review: Fix syntax and add additional licenses

.github/CODEOWNERS
Also just use dev-eng-leads and security-team as the approvers.
=> Expand CODEOWNERS to cover the entire repository

bot/internal/bot/assign.go, bot/internal/bot/assign_test.go
When requesting reviewers, we attempt to request reviews from those who reviewed the original PR. This can fail because the CodeQL scanner shows up as a reviewer.
Filter out bots by looking for '[bot]' in the reviewer name. This catches CodeQL and dependatbot, the two bots we have running at the time of this commit.
=> backport: don't request reviews from bots

bot/internal/bot/assign.go, bot/internal/bot/assign_test.go
The previous check handles cases where bots were assigned as reviewers, but failed to check for cases where bots had actually submitted reviews.
=> Fix for incorrectly assigning bots as reviewers

.github/workflows/dependency-review.yaml
Update dependency-review to also by default include the `master` branch.  In addition the minimal severity for failing was raised to moderate.
I think this will allow most projects to accept this configuration without modification.
=> Dependency-Review defaults update

.github/workflows/dependency-review.yaml
Currently this is failing even though all the licenses are listed as acceptable.  This commit attempts to add the exact license configuration needed by the dependent library `unicode-ident`.
=> Attempting to allow the Unicode license for rdp-rp

bot/internal/bot/backport.go, bot/internal/bot/bot.go, bot/internal/bot/bot_test.go, bot/internal/bot/check.go, bot/internal/github/github.go, bot/internal/review/review.go
If a PR author is not explicitly listed as an internal author in the reviewers secret, check whether the author is a member of the GitHub org.
This prevents us from having to maintain (and offboard) a list of every internal author, which is especially useful for employees from sales and CS who occaisonally submit PRs.
=> Consult GitHub org membership when identifying internal authors

bot/internal/github/github.go
The Go GitHub API that we use returns an error for repsonses with an HTTP status code not in the 200-299 range. This caused us to return an error rather than assume the user is an external author.
I noticed this when reviewing the logs of a recent run: https://github.com/gravitational/teleport/actions/runs/4018334113/jobs/6903826941
=> Fix an issue that prevents check from succeeding for external authors

bot/internal/review/review.go, bot/internal/review/review_test.go
The previous version of the code was checking whether the author was an external contributor twice, but the 2nd check happened at a level where we don't have enough information.
The 2nd check is not necessary, since it only occurs in the code path that is taken for internal authors. This commit includes a rename to make it clear that these methods are used for checking PRs from employees.
See https://github.com/gravitational/teleport/actions/runs/4029084130/jobs/6926613982 for an example run (prior to this fix) that correctly identifies an internal author and then changes its mind and thinks the author is external.
=> Fix checks for internal authors

bot/internal/review/review.go, bot/internal/review/review_test.go
Patch the review bot's preferred reviewers logic to prevent it from choosing too many reviewers. This change will not evaluate a path if that path has already been covered by a previously picked reviewer.
The current preferred reviewers implementation adds a reviewer for each unique path defined in the reviews.json file if that path is included in the change set. This can result in either the same reviewers being added multiple times, which Github dedups for us, or adds far too many reviewers when there are a large number of preferred paths in the change set.
Examples 
`2023/02/02 16:46:41 Assign: Requesting reviews from: [michellescripts sclevine sclevine michellescripts michellescripts dilchenko sclevine dboslee justinas evanfreed mcbattirola andreiko dboslee mcbattirola]` …
=> Covered paths for preferred reviewers

bot/internal/review/review.go, bot/internal/review/review_test.go
Removed admin reviewer assignment if admin is in omit list. This allows creation of admins that can still approve PRs but won't be assigned code reviews.
=> Removed admin reviewers with in omit list.

.github/workflows/codeql.yml, .github/workflows/csv-lint.yaml, .github/workflows/terraform-lint.yaml, .github/workflows/trivy.yaml
https://github.com/aquasecurity/tfsec/blob/master/docs/guides/trivy.md
tfsec is deprecated: https://github.com/aquasecurity/tfsec/discussions/1994
=> Add `tflint` to Terraform Lint, Add `trivy` workflow

.github/workflows/trivy.yaml
This option is needed to scan the config files the cloned repository files in the workspace (vs scanning images or remote repos).
=> Set the `trivy` `scan-type`

bot/internal/bot/backport.go
Each Github pull request can be fetched locally using `git fetch origin pull/<pr>/head`. If we use this instead of fetch the user-defined PR branch in the backport bot, we should be able to re-enable the setting that automatically deletes branches for merged PRs.
I did a quick test locally and `git fetch origin pull/<pr>/head` seems to work fine even on merged PRs with the deleted user branch.
=> Backport: fetch Github PR branch instead of head branch

bot/internal/bot/check.go, bot/internal/env/env.go
Most of our PRs for deploying to staging or production are large because they contain multiple PRs from master. Remove the need for admin approval for these cloud deployment branches.
=> Skip large PR check for cloud deploy branches

bot/main.go
1 minutes seems to be not enough and backport jobs are failing with `Workflow backport failed: context deadline exceeded.`.
=> Bump backport timeout to 5 minutes

.github/workflows/terraform-lint.yaml
It has been deprecated upstream, and use cases will migrate to using Trivy.
=> Deprecate tfsec

bot/main.go, bot/main_test.go
Reviewers are only required for assign or check workflows. This PR ensures that this is only checked for those workflows and introduces tests for argument parsing.
=> Only require reviewers for assign/check workflows.

.github/workflows/dependency-review.yaml
This adds:
* Python-2.0 (used by argparse@2.0.1)
* ISC AND MIT (already allowed individually, used by bcoe/v8-coverage@0.2.3)
Both are needed in Teleport as part of the latest version of Next
=> dependency-review: Additional License Approvals

bot/internal/bot/bot.go, bot/internal/bot/bot_test.go, bot/internal/bot/verify.go, bot/internal/bot/verify_test.go, bot/internal/github/github.go, bot/internal/github/github_test.go, bot/main.go
Add a new verify command for non-reviewer related checks. Include a DB migration filename verification for cloud.
This PR adds a new "verify" command intended to be used to verify a PR meets certain requirements. I thought about reusing the "check" command but that is intended to be specific to reviewers. There is also an argument for putting repo-specific verifications in the repo itself but keeping it here has the benefit of reusing code, secrets, and configs; and makes it easier to share if/when we want the same verification in multiple repos without having to mess with image publishing and versioning.
The specific check added ensures that migration files added to a PR have a timestamp that is newer than the most recent migration file timestamp in the base branch. This is needed to …
=> Add Verify command with Cloud migration check

bot/README.md, bot/internal/bot/bot.go, bot/internal/bot/bot_test.go, bot/internal/bot/check.go, bot/internal/bot/flake.go, bot/internal/bot/flake_test.go, bot/internal/github/github.go, bot/internal/review/review.go, bot/main.go
Teleport's flaky test detector looks for new or changed tests, and runs them many times in an attempt to detect flakiness. It's not very smart, so sometimes an inconsequential change to an old test (like renaming a variable or changing a function signature) will result in the detector trying to run a slow test too many times and timing out, blocking the team from merging the change.
This workflow will look at a PR and find /excludeflake comments from admins. This is intended to be used as a prerequisite to the flaky test detector, so that we can omit certain changes from flaky test detection.
Note: the flaky test detector itself lives in the Teleport repo. This will run first and pass output to the flaky test detector step.
See corresponding Teleport PR here: …
=> Add workflow to exclude flaky tests

.github/workflows/trivy.yaml
Reverts gravitational/shared-workflows#123.  Ever since this merged, Trivy has been failing with the folowing symptom:
```
Error: Code Scanning could not process the submitted SARIF file:
SARIF URI scheme "git" did not match the checkout URI scheme "file", <repeats>
```
https://github.com/gravitational/cloud-terraform/actions/runs/5294843544/jobs/9584603964?pr=2577
=> Revert "Bump aquasecurity/trivy-action from 0.10.0 to 0.11.2"

.github/workflows/dependency-review.yaml
https://gravitational.slack.com/archives/C03P3TY31HR/p1687454139319919
>  yarn.lock » pako@1.0.11 – License: MIT AND Zlib
>  yarn.lock » sha.js@2.4.11 – License: MIT AND BSD-3-Clause
Add the following licenses to the approved list:
* Zlib
* MIT AND Zlib
* MIT AND BSD-3-Clause
=> `dependency-review`: Approve several OSS licenses for new dependencies

bot/internal/bot/verify.go
The Github API requires a prefix in the git ref call to distinguish between branch and tag names. This fixes the verify workflow.
=> Fix Github API GetRef call in verify workflow

.github/workflows/dependency-review.yaml
`MIT-0` is the same as `MIT` but removes the attribution requirements: https://spdx.org/licenses/MIT-0.html
This can be seen from a variety of dependencies in this npm update: https://github.com/gravitational/docs/pull/335
=> Dependency Review: Add `MIT-0` License

.github/workflows/trivy.yaml
Addresses gravitational/secops#358
GitHub's code scanning can't handle SARIF locations other than plain repo-relative path strings, which trivy/defsec is emitting now that it is recursively scanning for all possible terraform root modules; filter these results out.
=> `trivy`: Filter git URIs from SARIF

.github/workflows/trivy.yaml
Addresses gravitational/SecOps#358
This disables Trivy for now, while we work on the check's false positives
=> Temporarily disable Trivy

.github/workflows/trivy.yaml
An empty steps list isn't supported. Print a message.
gravitational/SecOps#358
=> Disable Trivy

bot/internal/bot/assign.go, bot/internal/bot/bot.go, bot/internal/bot/bot_test.go, bot/internal/bot/check.go, bot/internal/env/changes.go, bot/internal/github/github.go, bot/internal/review/review.go, bot/internal/review/review_test.go
Update the bot's reviewers check to recognize release PRs (example: https://github.com/gravitational/teleport/pull/29308) and require at least one approval from the release team on them.
This is needed because our internal tool team folks are going to be publishing releases as well now and should be able to approve release PRs without being blocked on the admin approval. With this change, say if Trent is publishing release, he will be able to get an approval from Cam and another engineer (not necessarily on the release team) who are in the same timezone.
The list of release reviewers will be: Trent, Cam, Fred, Roman, Zac and Charn. I will update the [reviewers map](https://github.com/gravitational/github-terraform/blob/main/gravitational/secrets/reviewers.json) with this change before …
=> Update reviewers check for release PRs

.github/workflows/dependency-review.yaml
Inkeep doesn't use a SPDX license. This PR is created to pass license check on  https://github.com/gravitational/askpam/pull/1
This is their licence.
```
Inkeep, Inc. Customer License (IICL) v1.1
This license agreement ("Agreement") is a legal agreement between you (either an individual or a
single entity) and Inkeep, Inc. ("Inkeep") for the npm React component package `widgets` (the
"Software"). By installing, copying, or otherwise using the Software, you agree to be bound by the
terms of this Agreement.
1. Grant of License
Subject to the terms of this Agreement, Inkeep grants you a non-exclusive, non-transferable, limited license to install, copy, and use the Software solely for the purpose of serving Inkeep's search and chat services to your own end-users or employees. This license is …
```
=> Add Inkeep, Inc. Customer License (IICL) v1.1

bot/go.mod, bot/go.sum, bot/internal/bot/changelog.go, bot/internal/bot/changelog_test.go, bot/main.go
This allows for repos using the shared-workflows bot to enforce changelog requirements.
=> Added bot command to enforce changelog requirements

.github/dependabot.yml
I believe this is why the flagged updates in PR #172 were missed.
=> Add `bot` to Dependabot for CVE updates

.github/workflows/dependency-review.yaml
* http://www.wtfpl.net/
* https://en.wikipedia.org/wiki/WTFPL
Note that Google has `WTFPL` in their 'forbidden' list of licenses for open source projects that people should not contribute to. However, we're not contributing here and only using software written under this license.
https://opensource.google/documentation/reference/patching#forbidden
This is being added to address the addition of `@cspell/dict-django`, which uses it.
https://github.com/gravitational/docs/actions/runs/6661528177/job/18461330208?pr=410
=> Add `WTFPL` as a permitted license

.github/workflows/dependency-review.yaml
* Support passing more variables as inputs
* Lower threshold before blocking to `low` severity
* Add default `base-ref` and `head-ref` to fix merge queue issues
=> Improvements to `dependency-review` action

.github/workflows/dependency-review.yaml
We still use `master` several places, so need to use the default branch variable.
=> Use variable for default branch instead of hardcoding `main`

.github/workflows/dependency-review.yaml
To make failures from `dependency-review` more noticeable and actionable, enabling adding a comment in the PR on a failure state.
Should be backwards-compatible even if the calling action doesn't have `pull-requests` write permission.
=> `dependency-review`: Enable adding a comment in PR on failure

bot/internal/bot/check.go, bot/internal/review/review.go, bot/internal/review/review_test.go
The code reviewer configuration allows us to name preferred reviewers for certain file paths. For docs PRs, the workflow bot does not consult the preferred reviewer configuration. This means that, even if we add the `preferredReviewerFor` key to a `codeReviewers` entry with a docs path as a value, the workflow bot continues to add only `docsReviewers` to docs PRs.
In this change, the workflow bot gets docs reviewers by:
1. Retrieving the docs reviewer pool from the config (like it does now).
1. Retrieving all preferred reviewers for the file paths included within a PR. Since the pool of dedicated docs reviewers is small, the workflow bot gets all preferred reviewers for a file path, not just one.
1. Merging the two lists of reviewers.
The alternative would be to allow preferred file paths …
=> Allow preferred docs reviewers

.github/workflows/terraform-lint.yaml
We prefer to pin all GitHub Actions from a 3rd party in order to increase determinism and security for our workflows.
Contributes to https://github.com/gravitational/security-findings/issues/50
This should be merged before https://github.com/gravitational/shared-workflows/pull/188.
=> Pin terraform lint GitHub Actions

.github/workflows/github-action-lint.yaml
This workflow will check that all changed and added GitHub actions are either pinned to a hash, or on an allow list. This workflow is built to be reusable across Teleport repos, in addition to enforcing standards in this repo.
I chose to add it here to benefit from shared `dorny/paths-filter` logic as well as a common allow list of "safe actions".
Contributes to https://github.com/gravitational/security-findings/issues/50
I tested [a version of this workflow](https://github.com/wadells/gha-test/blob/acfbd373971851fb2d0d071beb6cc28feb50ded5/.github/workflows/lint-github-actions.yml) in [wadells/gha-test](https://github.com/wadells/gha-test).  Check out the follow pull request to see it in action:
https://github.com/wadells/gha-test/pull/3
I'll do further testing as we roll this out to …
=> Add GitHub Action to lint incoming GitHub Actions

.github/workflows/csv-lint.yaml, .github/workflows/json-lint.yaml
These actions both perform the same function.  However dorny/paths-filter has higher usage within the Teleport organization, and it is better to have one dependency to track/keep up to date instead of two.
=> Replace tj-actions/changed-files with dorny/paths-filter

.github/workflows/csv-lint.yaml, .github/workflows/json-lint.yaml
Reverts gravitational/shared-workflows#189.
Callers need additional permissions (`read: pull-request`) or they'll fail with the following signature:
https://github.com/gravitational/cloud-terraform/actions/runs/7091297245/job/19300146222?pr=3784
```
Fetching list of changed files for PR#3784 from Github API
Invoking listFiles(pull_number: 3784, per_page: 100)
Error: Resource not accessible by integration
```
Rolling back for now.  I'll look at updating call sites and then rolling back forward.
This is because `dorny/paths-filter` uses the github api to read diffs instead of `tj-actions` using the git history of the local checkout.  At least that is what my initial research suggests.
=> Revert "Replace tj-actions/changed-files with dorny/paths-filter"

.github/workflows/dependency-review.yaml
This check does not support repositories with multiple licenses due to the way the license query logic is implemented upstream. This PR adds an exception for the Teleport API package, which will affect all repos using this artifact.
This syntax is not very pretty, but this is the most simple solution that I could come up with due to GHA expression weirdness.
Tested via https://github.com/gravitational/cloud/pull/6901
=> Fixed `dependency-review` check failing on Teleport API

bot/internal/bot/verify.go, bot/internal/env/env.go, bot/main.go
Corresponding CI changes in `access-graph`: https://github.com/gravitational/shared-workflows/pull/185 (WIP)
* Adds ability to check for DB migration errors in the `access-graph` repo
* Makes `reviewers` parameter optional when not running `assign` or `check` workflows
* Improves logging, including a stack trace when the workflow exits with an error
=>  Add verification of DB migrations for access-graph 

bot/internal/bot/backport.go, bot/internal/bot/backport_test.go, bot/internal/bot/bot.go, bot/internal/bot/bot_test.go, bot/internal/bot/changelog.go, bot/internal/bot/changelog_test.go
With the new requirement of specifying changelog in the PR body or no-changelog label there's a problem with automatic backports, since they automatically fail those requirements. This PR improves backporting procedure by copying changelog message from the parent PR if it's present, or setting no-changelog label.
=> Automatically copy changelog message to the backport or put no-changelog label

.github/workflows/csv-lint.yaml, .github/workflows/json-lint.yaml
`printf %q` is a useful feature whenever we need to provide the input into a shell command.  It will escape characters which could be used for injection.
This PR fixes https://github.com/gravitational/security-findings/issues/52
=> csv-lint & json-lint: Use `printf %q` to sanatize input and avoid command injection

bot/internal/bot/verify.go, bot/internal/bot/verify_test.go
Exclude down migration files from the verify check. Only the up files are applied during deployment and some [recent PRs](https://github.com/gravitational/cloud/pull/7074) modified an old down migration file which [prevented the verify workflow from succeeding](https://github.com/gravitational/cloud/actions/runs/7278259607/job/19832056114).
=> verify: Exclude down migration files

bot/internal/bot/assign.go, bot/internal/bot/bot.go, bot/internal/bot/bot_test.go, bot/internal/bot/check.go, bot/internal/env/changes.go, bot/internal/review/review.go, bot/internal/review/review_test.go
This PR addresses the "Single Approver" issue described in #205.
Add the ability for certain PRs to require a single approval. 
A new setting has been added, singleApproverPaths, that defines paths in a repository that only require a single approver. If all the files in a PR only match paths defined in singleApproverPaths, then the PR only requires a single approval. Otherwise, the PR requires the default number of approvals, which is currently defined as 2.
A second setting was added, singleApproverAuthors, that defines PR authors that only require a single approval (dependency bots in cloud for now).
=> bot: Single Approval Paths

bot/internal/bot/bot.go, bot/internal/env/env.go, bot/internal/review/review.go, bot/internal/review/review_test.go, bot/main.go
This PR addresses the "Cross-Repo Reviewers" issue described in https://github.com/gravitational/shared-workflows/issues/205.
The current bot configuration data model doesn't allow an engineer to be a reviewer in both the cloud and core repositories. This is an issue because we now require the core team to submit PRs to the cloud repo to manage either tools they own (e.g. release server) or deploy a new version of a component they own (e.g. TAG). 
This PR provides a hacky solution that will allow us to change the bot config data model to include a cloud and core team section, while keeping the original code reviewers map in the bot so we don't have to change a large amount of code.
=> bot: Allow the same reviewer in both core and cloud repos

bot/go.mod
The review bot was updated to use the slices package and requires Go 1.21. We've changed the check workflow to use the stable version but need this PR to allow those fixes to pass the checks.
=> fix: review bot version

bot/internal/bot/check.go, bot/internal/review/review.go, bot/internal/review/review_test.go
#206 added support for a single approver but did not include single approvers from group B. 
1. Updated the check logic to allow a single approval from setB
2. Added use cases to the internal unit test 
3. Added a log line to print the number of required approvers for a PR
=> bot: Allow setB to be a single approver

bot/internal/bot/bot.go, bot/internal/review/review_test.go
Many of the downstream actions that use this bot don't execute using the most recent Go version. Downgrade the slices package to use `golang.org/x/exp/slices` rather than the stdlib version only available in 1.21.5.
=> fix: Revert slices package from stdlib

bot/internal/bot/bot.go
CRDs are generated and always causing large diffs requiring admin approval, even without meaningful changes.
This change allows us to add a new resource to the operator without admin approval.
=> Ignore generated CRDs during size check

bot/internal/bot/bot.go
https://github.com/gravitational/teleport/pull/37009 uses a new library for protobufs which have a slightly different suffix than existing files. This PR makes it so that the bot ignores those files during size check, just like other generated protobuf files.
=> Ignore new TypeScript protobufs during size check

bot/internal/bot/bot.go, bot/internal/bot/bot_test.go, bot/internal/review/review.go
This PR adds the ability to include a wildcard token (asterisk) in single approver paths. An asterisk will only match one path element (file/folder name) and does not span path-separators -- we don't get `.gitignore` style glob matching out of this change.
Wildcards are added to support a set of single approver files from the FluxCD portion of the cloud repo:
- `helmrelease.yaml` files contain the helm chart version which frequently gets updated during component upgrade
- `values.helm.yaml` files define a `configmap` that is fed into the `helmrelease` as values, we make changes to the values if we need to override an image version.
=> cloud/fluxcd: Single reviewer for helm chart versions and image versions

bot/internal/bot/assign_test.go, bot/internal/bot/backport_test.go, bot/internal/bot/bloat_test.go, bot/internal/bot/bot_test.go, bot/internal/bot/check_test.go, bot/internal/bot/flake_test.go, bot/internal/bot/skip_test.go, bot/internal/review/review.go, bot/internal/review/review_test.go
Fix an issue with cloud repo assignments, remove the Team field, and add a `preferredOnly` flag.
Context: our reviewer data model was changed last month to allow core team members to review code in the cloud repository. The new team maps (CoreReviewers and CloudReviewers) can include both core and cloud engineers.
1. **Fix Issue:** core team members submitting changes to the cloud repo were treated as external contributors because the internal check when getting reviewers was not checking the new team maps  (CoreReviewers & CloudReviewers).
2. **Remove the Team field:** since we’ve moved team assignments (core vs cloud vs docs) to distinct maps, this team field is not longer required and keeping it created ambiguity. It was previously used to determine which team (core vs cloud vs …
=> bot: Fix cloud reviewer assignments

bot/internal/review/review.go
Change the repoReviewers func so it returns cloud reviewers for the cloud repo and core reviewers for all other repos.
Fixes [this issue](https://gravitational.slack.com/archives/C0DF0TPMY/p1707579683890689) reported in Slack.
=> bot: Fix reviewers in non-teleport/cloud repos

bot/internal/review/review.go
Log the number of reviewers loaded in order to help debug issues loading the reviewers data.
=> bot: Log the number of reviewers loaded

bot/internal/review/review.go, bot/internal/review/review_test.go
Fix the preferred only feature for external authors who are assigned admin reviewers.
=> bot: Fix preferred only filter for external authors

bot/internal/bot/bot_test.go, bot/internal/review/review.go
Some of our flux source folders contain multiple `helmrelease.yaml` and `values.yaml` files. This PR adds wildcards to the filenames to support these scenarios.
=> bot: single-reviewer for multiple helmrelease/values in same folder

.github/workflows/dependency-review.yaml
Both licenses are already listed, but we need to explicitly declare the possibility of a dual license.
=> dependency-review - Add `BSD-2-Clause AND BSD-3-Clause` license

bot/internal/bot/bot.go
https://github.com/gravitational/teleport/pull/39230 switches the gRPC client from `grpc-js` to `protobuf-ts`. This PR makes it so that the bot ignores `protobuf-ts` files during size check, just like other generated protobuf files.
I didn't remove `_pb.grpc-client.ts`, because we still have a `grpc-js` protobufs in the shared process in Connect.
=> Ignore `protobuf-ts` client files during size check

.github/workflows/csv-lint.yaml, .github/workflows/json-lint.yaml
No functional change. This fixes [the "check github actions" workflow failures](https://github.com/gravitational/shared-workflows/actions/runs/8473925309/job/23219276923?pr=237) occurring on unrelated PRs.
=> Pin GHA dependencies to SHA

.github/workflows/dependency-review.yaml
This PR allows us to import teleport without causing a license error.
This is required for https://github.com/gravitational/teleport/pull/40224
=> exclude Teleport license from the license check

.github/CODEOWNERS
This change will ensure we've got the right review processes in place while the former maintainers are still around to help with changes. We're approaching two weeks out from that cutoff.
Particular to this repo, I think we may want to add some Tools reviewers.
cc @fheinecke @camscale
=> Remove `shared-workflows` Security CODEOWNERS

.github/workflows/dependency-review.yaml
We noticed breakage when the last version landed (~33 minutes ago).   After closer inspection it looks like they intended to only scope the changes to a subset but it has impacted more than anticipated.  This should restore stability until upstream corrects and re-releases the fix.
=> Pin dependency-review-action

bot/internal/bot/bot.go
Changes fx in web code might lead to large amount of lines in snapshot files which results in unnecessary requirement of admin approval for a PR.
=> Ignore snapshot files during PR size check.

bot/internal/github/github.go
Fixes the bot comment listing pagination logic.
The options were never passed properly so for large PRs with many comments, we fell into an infinite loop.
=> fix comment listing pagination

libs/git/git.go
Git library didn't handle the timestamp returned from `git log --format=%cd` very well for days that are one digit e.g. `Aug 8 2024` couldn't be handled but `Aug 08 2024` could. To just simplify it and be less ambiguous the git format will now be ISO 8601 and time parsing will now handle that.
=> Git library will use ISO 8601 format for consistency

tools/changelog/go.mod, tools/changelog/go.sum
This fixes the `api.github.com` issue and will now return the proper URL.
=> Bumping dependency version for libs

libs/git/git.go, libs/github/pull_request.go
Use the standard `time.RFC3339` time format with `time.Parse()` so that
we support dates with a `Z` suffix instead of just a UTC offset. The
simple `Z` format is allowed by ISO8601 format so we should parse that.
It turns out that the `%cI` format passed to `git show` will return the
format with the `Z` suffix.
This fixes an error when running the changelog tool:
parsing time "2024-09-25T02:35:11Z" as "2006-01-02T15:04:05-07:00": cannot parse "Z" as "-07:00"
Change the form of the github query date formatting to use `>=` instead
of `>` when just a start date is provided. The makes it consistent with
the range format (`a..b`) used when an end date is provided as the range
includes the first date. The changelog tool will need to be updated to
handle this by bumping the start dates by 1 …
=> libs: Fix some git/github date/time issues

.github/workflows/dependency-review.yaml
Checks started failing this evening with:
The following dependencies have incompatible licenses:
pnpm-lock.yaml » sprintf-js@1.0.3 – License: BSD-3-Clause AND BSD-3-Clause-Clear
The sprintf-js library is very old (1.0.3 was published 9 years ago), and it is very clearly a standard 3-clause BSD license [1].
The recent failure is probably something to do with the database used by the dependency-review-action.
[1] https://github.com/alexei/sprintf.js/blob/1.0.3/LICENSE
=> dependency review: add BSD variant

tools/changelog/go.mod, tools/changelog/go.sum, tools/changelog/main.go
Use libs/v0.1.3 for fixed time parsing for ISO8601 times with a `Z`
suffix, and adjust our commit time query to account for an boundary
condition error resulting in the occasional PR appearing in the
changelog of 2 releases.
---
I ran this version against the 16.4.0 and 16.4.1 release where the
previous version duplicated a changelog entry in each release and
verified that no longer happened.
=> changelog: Use fixed time parsing, adjust time query boundary

tools/env-loader/README.md, tools/env-loader/pkg/envloader.go
This is a minor change to the environment loader tool to allow for loading values from additional "common" files.
Previously, if an environment name contained a slash (i.e. `publish/prod`), the following file globs would be loaded:
* `<root env dir>/common.*`
* `<root env dir>/publish/prod/common.*`
This PR splits the name into components using the `/` character as a separator (on all platforms), and checks each part. Now, the following file globs would be loaded:
* `<root env dir>/common.*`
* `<root env dir>/publish/common.*`
* `<root env dir>/publish/prod/common.*`
This small but powerful change will greatly reduce the amount of duplication we have in cases [like this](https://github.com/gravitational/github-terraform/blob/main/gravitational/github-actions-values.tf#L293-L317).
=> Changed environment loader to split environment names on '/'

tools/env-loader/cmd/env-loader.go, tools/env-loader/pkg/envloader.go, tools/env-loader/pkg/envloader_test.go, tools/env-loader/pkg/testdata/repos/basic repo/.environments/env1/testing1.abc, tools/env-loader/pkg/testdata/repos/basic repo/.environments/env1/testing2.abc
This adds env-loader support for loading multiple value sets. Examples:
```shell
env-loader --environment stage/build
env-loader --environment stage/publish --value-set amis
env-loader --environment prod/publish --value-set gpg-signing --value-set os-package-repos
VALUE_SETS="$(
cat << EOF
gpg-signing
os-package-repos
EOF
)"  # Mock - this is the format provided by GHA
echo "${VALUE_SETS}" | while read -r line; do
env-loader --environment prod/publish --value-set "${line}"
done
```
The diff is somewhat messy but this essentially amounts to changing a CLI arg to a list type, and plumbing it to a `for` loop.
=> Added support for loading multiple value sets

tools/env-loader/cmd/env-loader.go
Forgot to plumb this to the CLI when I implemented it in the original PR.
=> env-loader: Allow for providing environments directory via arg

.github/workflows/reusable-cd.yaml, tools/env-loader/Makefile, tools/repo-release-tooling/tooling.mk
The env-loader release is failing due to this. Trim `/` from the version, and check only the `VERSION` to determine if a release is a prerelease or not.
=> Fix tooling release issues

tools/env-loader/cmd/env-loader.go, tools/env-loader/cmd/env-loader_test.go, tools/env-loader/pkg/envloader.go, tools/env-loader/pkg/envloader_test.go
Fixed the following bugs with the env loader tool:
* `environments-directory` arg shared an environment variable with the `environments` arg
* No output would be produced if no values were specifically requested, instead of outputting all loaded values
* Git repo root not properly detected when the repo is a submodule
* Environment names with a `/` character in them would search individual components instead of the full path (i.e. `.environments/stage` and `.environments/build` instead of `.environments/stage/build`)
=> env-loader: bug fixes

tools/env-loader/pkg/envloader_test.go, tools/env-loader/pkg/loaders/subloader_test.go, tools/env-loader/pkg/loaders/yaml_test.go, tools/env-loader/pkg/values/value.go, tools/env-loader/pkg/values/value_test.go, tools/env-loader/pkg/writers/gha-mask_test.go, tools/env-loader/pkg/writers/writer_test.go
A few env-loader files are missing license headers. This adds them.
=> env-loader: Added missing license headers

.github/workflows/dependency-review.yaml
Checks began failing this evening with the following issue:
The dependencies listed below have incompatible licenses:  
- `pnpm-lock.yaml » prettier@3.4.2` – License: Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND ISC AND MIT  
- `pnpm-lock.yaml » rollup@4.28.1` – License: 0BSD AND ISC AND MIT  
The `rollup` library itself is licensed under MIT, but some of its dependencies are under ISC and 0BSD licenses [1].  
Similarly, `prettier` is released under the MIT license, but several of its dependencies use other licenses [2].
[1] https://github.com/rollup/rollup/blob/master/LICENSE.md
[2] https://github.com/prettier/prettier/blob/main/LICENSE
=> dependency review: add 0BSD and Apache-2.0 variants

tools/env-loader/pkg/writers/gha-env.go, tools/env-loader/pkg/writers/gha-env_test.go, tools/env-loader/pkg/writers/writer.go
This adds a new writer specifically for writing to `GITHUB_ENV` files. [This format](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable) is _close_ to dotenv files, but doesn't actually match it for multiline strings.
Here's an example output:
```
key1<<EOF
multiline
value1
EOF
key2=value2
key3<<EOF
multiline
value3
EOF
```
Here's what it looks like for dotenv:
```
key1=multiline
value1
key2=value2
key3=multiline
value3
```
As shown above, dotenv doesn't handle new lines at all, and errors in this case as shown [here](https://github.com/gravitational/teleport.e/actions/runs/12421540569/job/34681591637#step:4:134).
While this is more GHA-specific logic, it is a necessary evil. We'll need …
=> env-loader: Added gha-env writer

.github/workflows/dependency-review.yaml
Similar to https://github.com/gravitational/shared-workflows/pull/305/ this PR will add another variant/combo and various licenses. Idealy we could manage this in some sort of "check if each of these invidually" are included, but idk how the legallity of licenses work so Ill just follow prior work here
related PR failure
https://github.com/gravitational/teleport/actions/runs/12911052502/job/36002924223?pr=51356#step:3:19
=> Add Apache-2.0 variant

.github/workflows/reusable-ci.yaml, tools/env-loader/README.md, tools/env-loader/action.yaml
This adds an action that will be used to run the environment value loader in release pipelines.
Depends on https://github.com/gravitational/shared-workflows/pull/284, #286.
=> Added action for env-loader

tools/env-loader/Makefile
This will create a release for the GH action used in our release pipelines.
=> Release env-loader v0.0.5

.github/workflows/dependency-review.yaml
We have a dependency update in the web packages that are failing due to some missing licenses/variants. From [reading our open source policy](https://github.com/gravitational/company-policies/blob/2a3a81e695941cfeb035b0fe6a1ca30792d10aef/Open-Source-Policy.md#open-source-use) ibelieve these licenses fall under "good to go". 
https://github.com/gravitational/teleport/actions/runs/13166964916/job/36749302798?pr=51767#step:3:19
=> Add MIT unicode variant

bot/internal/bot/docpaths.go, bot/internal/bot/docpaths_test.go
The workflow currently fails if the event is not a pull request, since it attempts to list files for a PR with number 0 and receives a 404 from the GitHub API. Edit the workflow so it does not return an error if the event is not a PR.
=> [bot] Allow for non-PR events in docpaths

bot/internal/bot/docpaths.go, bot/internal/bot/docpaths_test.go
The docpaths workflow currently blocks pull requests that rename or delete partials, which is not intended: the docs engine does not generate routes for partials.
This change skips redirect checking for any file path that includes the `/includes/` segment. This follows the logic of the docs engine, which checks whether a page path includes the `/includes/` segment and, if not, moves it into the directory that Docusaurus uses to generate page routes.
=> [bot] Ignore includes in docpaths

bot/main.go, bot/main_test.go
The shared-workflows bot currently only supports decoding the `--reviewers` flag as a base64-encoded JSON string. For example, rather than
```json
{
"reviewer-group-1": {
"username": {
... // Repeat for 100+ lines
```
the tool requires the value as `ewogICJyZXZpZXdlci1ncm91cC0xIjogewogICAgInVzZXJuYW1lIjogewogICAgICAgIC4uLiAvLyBSZXBlYXQgZm9yIDEwMCsgbGluZXMK...`. For those of us who cannot base64-decode a string in their head, this is really difficult to read and debug.
Previously this was needed because GHA environment variables/secrets do not "play nice" with structured multiline data. However, now that we're starting to use [`env-loader`](https://github.com/gravitational/shared-workflows/tree/main/tools/env-loader) for these values, we can support plain-text JSON without issue.
This …
=> Support decoding `--reviewers` as plain-text JSON

.github/workflows/dependency-review.yaml
The job will fail if the comment it tries to post to the PR is too large. This is fixed in newer versions of the action, but there are other breaking changes to navigate if we want to update so the quick fix for now is to disable comment summaries.
=> dependency review: disable comment summary

.github/workflows/dependency-review.yaml
We want at least v4.3.3 in order to get the fix from https://github.com/actions/dependency-review-action/pull/767 that prevents large summaries from failing the job.
=> Update dependency-review action

.github/workflows/csv-lint.yaml, .github/workflows/json-lint.yaml
Add quotes around `*` to fix failures like:
```
Error: unidentified alias "*/*.csv" (2:13)
1 | csv:
2 |   - **/*.csv
-----------------^
```
=> gha(path-filter) fix quotes

tools/changelog/changelog.go, tools/changelog/changelog_test.go, tools/changelog/main.go, tools/changelog/testdata/expected-cl-no-links.md
Do not link to PRs for enterprise changelogs as that is a private repo
and the links will not work for most. Given that the changelog is
published in the OSS repo, it does not make sense to include private
links.
=> changelog: Do not add PR links for enterprise changelogs

bot/internal/review/review.go, bot/internal/review/review_test.go
Currently if a person is on `codeReviewersOmit` list their approval no longer satisfies the "internal reviewers" check. 
My understanding is that this is incorrect, as `codeReviewersOmit` was meant to reduce the workload of busy people while keeping their permissions intact.
This PR fixes that behaviour.
=> Honor approvals from people on `codeReviewersOmit` list

.github/workflows/terraform-lint.yaml
`tflint` does not run recursively by default, so this is only executing against the repo root, which often does nothing.
=> Fix tflint implementation

.github/workflows/terraform-lint.yaml
https://github.com/gravitational/shared-workflows/pull/343 fixed this check recently. Some repos have lots of warnings ([cloud-terraform](https://github.com/gravitational/cloud-terraform/actions/runs/14132000344/job/39594447742?pr=6318)) and may wish to ignore them for the time being. Make the failure severity configurable.
=> Make tflint failure severity configurable

.github/workflows/terraform-lint.yaml
Teleport repo has lots of [failures](https://github.com/gravitational/teleport/actions/runs/14179688579/job/39722703386#step:8:162), some at the error level. Instead of chasing them all right now enable forcing a 0 exit status. This is necessary because the config file `force` option doesn't work with the `--recursive` flag.
=> Expose force option in tflint workflow

bot/internal/bot/bot.go
This directory holds copied protos for the Teleport Kubernetes Operator, and can cause diffs of thousands of lines when new resources are being introduced.
=> Exclude testdata proto directory for operator

.github/workflows/dependency-review.yaml
The dependency review tool now reports protobuf.js's license as `BSD-3-Clause AND LicenseRef-scancode-protobuf`. I'm not entirely sure why, it might be due to the license being a custom one? https://github.com/protobufjs/protobuf.js/blob/master/LICENSE
protobuf.js is now a dependency of the tool `@redocly/cli` we use in Identity Security to stitch OpenAPI spec files together. Upgrading to the latest version resulted in this dependency error. https://github.com/gravitational/access-graph/pull/1553
=> dependency review: add license for protobuf.js

.github/workflows/reusable-ci.yaml, tools/amplify-preview/github.go, tools/env-loader/cmd/env-loader_test.go, tools/env-loader/pkg/loaders/yaml_test.go, tools/repo-release-tooling/tooling.mk
Remove the `--out-format colored-line-number` as that is no longer
present on golangci-lint 2.0+, and if that later version is installed,
`make lint` fails.
Only pass `--format github-actions` to `gotestsum` if we are running on
GitHub Actions. The output is rather verbose / noisy for locally running
`make test`.
Update golangci-lint from 1.61.0 to 2.3.0 as 1.61.0 does not seem to
properly handle the later (1.23+) versions of Go.
Have the reusable-ci workflow run if that workflow file itself changes,
not just stuff in the tools directory. This makes sure that all tools
are kept up-to-date with the tooling.
Fix newly-surfaced lint errors in amplify-preview and env-loader. Ignore
errors in approvals-service as they are being fixed in another PR.
=> tools/common: Rework output for common test and lint

tools/approval-service/internal/service/githubapproval.go, tools/approval-service/internal/service/releaseservice.go
Currently the Approval Service will make decisions on Deployment Protection Rules with the comment `Decision made by the approval service based on Access Request state`. This isn't a very useful summary of what occurred.
This PR introduces updates to the comment so that it contains the Access Request ID and the users who approved the Access Request. As an example of the new format: `Access Request "45edb351-a02f-4ecb-9d5d-7e2ec1a91844" was approved by gus.rivera@goteleport.com. This decision was made by the approval service based on Access Request state.`
=> Approval Service - Improve comment for Deployment Protection Rules decisions

tools/repo-release-tooling/tooling.mk
This change sets`CGO_ENABLED=0` for our binary builds in the shared tooling Makefile. This should force Go to always build statically linked binaries.
When building linux/amd64 binaries in CD, we would get a dynamically linked binary which would not run on our distroless containers because the C Toolchain is missing. This only affected the linux/amd64 binaries because it was being build on a native host (the runner is also linux/amd64).
=> Setting CGO_ENABLED=0 for our binary builds
